(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)
(*                                                                             *)
(*         This file has been automatically generated by FeynRules.            *)
(*                                                                             *)
(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)


FR$ModelInformation={
  ModelName->"DF",
  Authors -> {"YC", "XZ"},
  Version -> "0.1"};

FR$ClassesTranslation={};

FR$InteractionOrderPerturbativeExpansion={{QED, 0}};

FR$GoldstoneList={};

(*     Declared indices    *)

IndexRange[ Index[Generation] ] = Range[ 3 ]

(*     Declared particles    *)

M$ClassesDescription = {
F[1] == {
    SelfConjugate -> False,
    QuantumNumbers -> {LeptonNumber},
    PropagatorLabel -> "Snu",
    PropagatorType -> ScalarDash,
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {} },

F[2] == {
    SelfConjugate -> False,
    Indices -> {Index[Generation]},
    QuantumNumbers -> {Q, LeptonNumber},
    PropagatorLabel -> "l",
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> Ml },

F[5] == {
    SelfConjugate -> False,
    QuantumNumbers -> {Q},
    PropagatorLabel -> "Proton",
    PropagatorType -> ScalarDash,
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> Mproton,
    Indices -> {} },

F[6] == {
    SelfConjugate -> False,
    QuantumNumbers -> {LeptonNumber},
    PropagatorLabel -> "Nu",
    PropagatorType -> ScalarDash,
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {} },

V[1] == {
    SelfConjugate -> True,
    PropagatorLabel -> "\\gamma",
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> 0,
    Indices -> {} },

S[1] == {
    SelfConjugate -> True,
    PropagatorLabel -> "s1",
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> Mds,
    Indices -> {} }
}


(*        Definitions       *)


Ml[ 1 ] := Me;
Ml[ 2 ] := MMU;
Ml[ 3 ] := MTA;
Mproton[ ___ ] := Mproton;
Mds[ ___ ] := Mds;


TheLabel[ F[2, {1}] ] := "e";
TheLabel[ F[2, {2}] ] := "mu";
TheLabel[ F[2, {3}] ] := "ta";


(*      Couplings (calculated by FeynRules)      *)

M$CouplingMatrices = {

C[ -F[2, {e1x2}] , F[2, {e2x2}] , S[1] ] == {{I*gc1L*IndexDelta[e1x2, e2x2], 0}, {I*gc1R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[2, {e1x2}] , F[2, {e2x2}] , V[1] ] == {{I*gc2*IndexDelta[e1x2, e2x2], 0}, {I*gc2*IndexDelta[e1x2, e2x2], 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[5] , F[5] , V[1] ] == {{I*gc3, 0}, {I*gc3, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[6] , F[1] , V[1] ] == {{0, 0}, {0, 0}, {(-I)*muNuN, 0}, {(-I)*muNuN, 0}, {I*muNuN, 0}, {I*muNuN, 0}},

C[ -F[1] , F[6] , V[1] ] == {{0, 0}, {0, 0}, {(-I)*muNuN, 0}, {(-I)*muNuN, 0}, {I*muNuN, 0}, {I*muNuN, 0}}

}

(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)

(* Parameter replacement lists (These lists were created by FeynRules) *)

(* FA Couplings *)

M$FACouplings = {
     gc1L -> -EL,
     gc1R -> EL,
     gc2 -> EL,
     gc3 -> EL};

